[package]
name = "towbootctl"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpt = "3.1"
fscommon = "0.1"
fatfs = "0.3"
log = "0.4.4"
