on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install Rust for i686
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  override: true
                  target: i686-unknown-uefi
            - name: Install Rust for x86_64
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  override: true
                  target: x86_64-unknown-uefi
            - name: Build for i686
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --target i686-unknown-uefi
            - name: Upload i686 artifact
              uses: actions/upload-artifact@v2
              with:
                  name: towboot-debug-i686.efi
                  path: target/i686-unknown-uefi/debug/towboot.efi
            - name: Build for x86_64
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --target x86_64-unknown-uefi
            - name: Upload x86_64 artifact
              uses: actions/upload-artifact@v2
              with:
                  name: towboot-debug-x86_64.efi
                  path: target/x86_64-unknown-uefi/debug/towboot.efi
