on:
    push:
        branches:
        tags: 'v*'
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Rust for i686
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  override: true
                  target: i686-unknown-uefi
            - name: Install Rust for x86_64
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: nightly
                  override: true
                  target: x86_64-unknown-uefi
            - name: Build for i686
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --package towboot --target i686-unknown-uefi --release
            - name: Build for x86_64
              uses: actions-rs/cargo@v1
              with:
                  command: build
                  args: --package towboot --target x86_64-unknown-uefi --release
            - name: Rename files (1)
              run: cp target/i686-unknown-uefi/release/towboot.efi towboot-$(git describe --always --tags)-i686.efi
            - name: Rename files (2)
              run: cp target/x86_64-unknown-uefi/release/towboot.efi towboot-$(git describe --always --tags)-x86_64.efi
            - name: Publish release
              uses: softprops/action-gh-release@v1
              with:
                files: |
                    towboot-*-i686.efi
                    towboot-*-x86_64.efi
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
